spring.application.name=user
server.port=8082


# Cada propiedad en su renglón para que Spring Boot lo lea sin fallos
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:ms-usuario}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# CONFIGURACIÓN DE JPA HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# CONFIGURACIÓN FLYWAY
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# CONFIGURACIÓN DE LOGS
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=INFO

# SEGURIDAD JWT (Compartida entre todos tus servicios)
jwt.secret=${JWT_SECRET:mysecreto98765432112345698778912}

#INTEGRACIÓN CON EL SERVIDOR DE DESCUBRIMIENTO EUREKA

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true