spring.application.name=ms-cocina
server.port=${PORT:8085}

spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:cocina_coffee}
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

logging.level.org.springframework.web=INFO
logging.level.org.hibernate=INFO
logging.level.com.example.ms_cocina=INFO
logging.file.name=logs/ms-cocina.log

jwt.secret=${JWT_SECRET:mysecreto98765432112345698778912}

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true

springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/v3/api-docs