CREATE DATABASE IF NOT EXISTS pedidos_coffee;
CREATE DATABASE IF NOT EXISTS cocina_coffee;
CREATE DATABASE IF NOT EXISTS cupones_coffee;
CREATE DATABASE IF NOT EXISTS `ms-usuario`;
CREATE DATABASE IF NOT EXISTS db_menu;
CREATE DATABASE IF NOT EXISTS db_pagos;
CREATE DATABASE IF NOT EXISTS db_fidelidad;
CREATE DATABASE IF NOT EXISTS db_inventario;
CREATE DATABASE IF NOT EXISTS db_resena;
CREATE DATABASE IF NOT EXISTS db_aviso;

CREATE USER IF NOT EXISTS 'appuser'@'%' IDENTIFIED BY '1234';
GRANT ALL PRIVILEGES ON pedidos_coffee.* TO 'appuser'@'%';
GRANT ALL PRIVILEGES ON cocina_coffee.* TO 'appuser'@'%';
GRANT ALL PRIVILEGES ON cupones_coffee.* TO 'appuser'@'%';
GRANT ALL PRIVILEGES ON `ms-usuario`.* TO 'appuser'@'%';
GRANT ALL PRIVILEGES ON db_menu.* TO 'appuser'@'%';
GRANT ALL PRIVILEGES ON db_pagos.* TO 'appuser'@'%';
GRANT ALL PRIVILEGES ON db_fidelidad.* TO 'appuser'@'%';
GRANT ALL PRIVILEGES ON db_inventario.* TO 'appuser'@'%';
GRANT ALL PRIVILEGES ON db_resena.* TO 'appuser'@'%';
GRANT ALL PRIVILEGES ON db_aviso.* TO 'appuser'@'%';
FLUSH PRIVILEGES;
