services:

  mysql-pedidos:
    image: mysql:8
    container_name: mysql-pedidos
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pedidos_coffee
      MYSQL_USER: appuser
      MYSQL_PASSWORD: 1234
    ports:
      - "3307:3306"
    volumes:
      - mysql_pedidos_data:/var/lib/mysql
    networks:
      - backend-network

  mysql-cocina:
    image: mysql:8
    container_name: mysql-cocina
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cocina_coffee
      MYSQL_USER: appuser
      MYSQL_PASSWORD: 1234
    ports:
      - "3308:3306"
    volumes:
      - mysql_cocina_data:/var/lib/mysql
    networks:
      - backend-network

  mysql-cupones:
    image: mysql:8
    container_name: mysql-cupones
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cupones_coffee
      MYSQL_USER: appuser
      MYSQL_PASSWORD: 1234
    ports:
      - "3309:3306"
    volumes:
      - mysql_cupones_data:/var/lib/mysql
    networks:
      - backend-network

  mysql-user:
    image: mysql:8
    container_name: mysql-user
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms-usuario
      MYSQL_USER: appuser
      MYSQL_PASSWORD: 1234
    ports:
      - "3310:3306"
    volumes:
      - mysql_user_data:/var/lib/mysql
    networks:
      - backend-network

  mysql-menu:
    image: mysql:8
    container_name: mysql-menu
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_menu
      MYSQL_USER: appuser
      MYSQL_PASSWORD: 1234
    ports:
      - "3311:3306"
    volumes:
      - mysql_menu_data:/var/lib/mysql
    networks:
      - backend-network

  mysql-pago:
    image: mysql:8
    container_name: mysql-pago
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_pagos
      MYSQL_USER: appuser
      MYSQL_PASSWORD: 1234
    ports:
      - "3312:3306"
    volumes:
      - mysql_pago_data:/var/lib/mysql
    networks:
      - backend-network

  mysql-fidelidad:
    image: mysql:8
    container_name: mysql-fidelidad
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_fidelidad
      MYSQL_USER: appuser
      MYSQL_PASSWORD: 1234
    ports:
      - "3313:3306"
    volumes:
      - mysql_fidelidad_data:/var/lib/mysql
    networks:
      - backend-network

  mysql-inventario:
    image: mysql:8
    container_name: mysql-inventario
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_inventario
      MYSQL_USER: appuser
      MYSQL_PASSWORD: 1234
    ports:
      - "3314:3306"
    volumes:
      - mysql_inventario_data:/var/lib/mysql
    networks:
      - backend-network

  mysql-resena:
    image: mysql:8
    container_name: mysql-resena
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_resena
      MYSQL_USER: appuser
      MYSQL_PASSWORD: 1234
    ports:
      - "3315:3306"
    volumes:
      - mysql_resena_data:/var/lib/mysql
    networks:
      - backend-network

  mysql-aviso:
    image: mysql:8
    container_name: mysql-aviso
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_aviso
      MYSQL_USER: appuser
      MYSQL_PASSWORD: 1234
    ports:
      - "3316:3306"
    volumes:
      - mysql_aviso_data:/var/lib/mysql
    networks:
      - backend-network

  ms-eureka:
    build: ./ms-eureka
    container_name: ms-eureka
    restart: unless-stopped
    ports:
      - "8761:8761"
    networks:
      - backend-network

  ms-pedidos:
    build: ./ms-pedidos
    container_name: ms-pedidos
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      DB_HOST: mysql-pedidos
      DB_PORT: 3306
      DB_NAME: pedidos_coffee
      DB_USER: appuser
      DB_PASSWORD: 1234
      JWT_SECRET: mysecreto98765432112345698778912
      EUREKA_URL: http://ms-eureka:8761/eureka/
    depends_on:
      - mysql-pedidos
      - ms-eureka
    networks:
      - backend-network

  ms-cocina:
    build: ./ms-cocina
    container_name: ms-cocina
    restart: unless-stopped
    ports:
      - "8085:8085"
    environment:
      DB_HOST: mysql-cocina
      DB_PORT: 3306
      DB_NAME: cocina_coffee
      DB_USER: appuser
      DB_PASSWORD: 1234
      JWT_SECRET: mysecreto98765432112345698778912
      EUREKA_URL: http://ms-eureka:8761/eureka/
    depends_on:
      - mysql-cocina
      - ms-eureka
      - ms-pedidos
    networks:
      - backend-network

  ms-cupones:
    build: ./ms-cupones
    container_name: ms-cupones
    restart: unless-stopped
    ports:
      - "8089:8089"
    environment:
      DB_HOST: mysql-cupones
      DB_PORT: 3306
      DB_NAME: cupones_coffee
      DB_USER: appuser
      DB_PASSWORD: 1234
      JWT_SECRET: mysecreto98765432112345698778912
      EUREKA_URL: http://ms-eureka:8761/eureka/
    depends_on:
      - mysql-cupones
      - ms-eureka
    networks:
      - backend-network

  user:
    build: ./user
    container_name: user
    restart: unless-stopped
    ports:
      - "8082:8082"
    environment:
      DB_HOST: mysql-user
      DB_PORT: 3306
      DB_NAME: ms-usuario
      DB_USER: appuser
      DB_PASSWORD: 1234
      JWT_SECRET: mysecreto98765432112345698778912
      EUREKA_URL: http://ms-eureka:8761/eureka/
    depends_on:
      - mysql-user
      - ms-eureka
    networks:
      - backend-network

  menu:
    build: ./menu
    container_name: menu
    restart: unless-stopped
    ports:
      - "8083:8083"
    environment:
      DB_HOST: mysql-menu
      DB_PORT: 3306
      DB_NAME: db_menu
      DB_USER: appuser
      DB_PASSWORD: 1234
      JWT_SECRET: mysecreto98765432112345698778912
      EUREKA_URL: http://ms-eureka:8761/eureka/
    depends_on:
      - mysql-menu
      - ms-eureka
    networks:
      - backend-network

  pago:
    build: ./pago
    container_name: pago
    restart: unless-stopped
    ports:
      - "8084:8084"
    environment:
      DB_HOST: mysql-pago
      DB_PORT: 3306
      DB_NAME: db_pagos
      DB_USER: appuser
      DB_PASSWORD: 1234
      JWT_SECRET: mysecreto98765432112345698778912
      EUREKA_URL: http://ms-eureka:8761/eureka/
    depends_on:
      - mysql-pago
      - ms-eureka
    networks:
      - backend-network

  fidelidad:
    build: ./fidelidad
    container_name: fidelidad
    restart: unless-stopped
    ports:
      - "8087:8087"
    environment:
      DB_HOST: mysql-fidelidad
      DB_PORT: 3306
      DB_NAME: db_fidelidad
      DB_USER: appuser
      DB_PASSWORD: 1234
      JWT_SECRET: mysecreto98765432112345698778912
      EUREKA_URL: http://ms-eureka:8761/eureka/
    depends_on:
      - mysql-fidelidad
      - ms-eureka
    networks:
      - backend-network

  inventario:
    build: ./inventario
    container_name: inventario
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      DB_HOST: mysql-inventario
      DB_PORT: 3306
      DB_NAME: db_inventario
      DB_USER: appuser
      DB_PASSWORD: 1234
      JWT_SECRET: mysecreto98765432112345698778912
      EUREKA_URL: http://ms-eureka:8761/eureka/
    depends_on:
      - mysql-inventario
      - ms-eureka
    networks:
      - backend-network

  resena:
    build: ./resena
    container_name: resena
    restart: unless-stopped
    ports:
      - "8090:8090"
    environment:
      DB_HOST: mysql-resena
      DB_PORT: 3306
      DB_NAME: db_resena
      DB_USER: appuser
      DB_PASSWORD: 1234
      JWT_SECRET: mysecreto98765432112345698778912
      EUREKA_URL: http://ms-eureka:8761/eureka/
    depends_on:
      - mysql-resena
      - ms-eureka
      - menu
    networks:
      - backend-network

  aviso:
    build: ./aviso
    container_name: aviso
    restart: unless-stopped
    ports:
      - "8088:8088"
    environment:
      DB_HOST: mysql-aviso
      DB_PORT: 3306
      DB_NAME: db_aviso
      DB_USER: appuser
      DB_PASSWORD: 1234
      JWT_SECRET: mysecreto98765432112345698778912
      EUREKA_URL: http://ms-eureka:8761/eureka/
    depends_on:
      - mysql-aviso
      - ms-eureka
    networks:
      - backend-network

  ms-gateway:
    build: ./ms-gateway
    container_name: ms-gateway
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      EUREKA_URL: http://ms-eureka:8761/eureka/
    depends_on:
      - ms-eureka
      - ms-pedidos
      - ms-cocina
      - ms-cupones
      - user
      - menu
      - pago
      - fidelidad
      - inventario
      - resena
      - aviso
    networks:
      - backend-network

volumes:
  mysql_pedidos_data:
  mysql_cocina_data:
  mysql_cupones_data:
  mysql_user_data:
  mysql_menu_data:
  mysql_pago_data:
  mysql_fidelidad_data:
  mysql_inventario_data:
  mysql_resena_data:
  mysql_aviso_data:

networks:
  backend-network:
    driver: bridge
