spring.application.name=ms-gateway
server.port=${PORT:8080}

spring.cloud.gateway.server.webmvc.routes[0].id=ms-pedidos
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://ms-pedidos
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/pedidos/**

spring.cloud.gateway.server.webmvc.routes[1].id=ms-cocina
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://ms-cocina
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/cocina/**

spring.cloud.gateway.server.webmvc.routes[2].id=ms-cupones
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://ms-cupones
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/cupones/**

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true
