spring.application.name=ms-gateway
server.port=${PORT:8080}

spring.cloud.gateway.server.webmvc.routes[0].id=ms-pedidos
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://ms-pedidos
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/pedidos/**

spring.cloud.gateway.server.webmvc.routes[1].id=ms-cocina
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://ms-cocina
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/cocina/**

spring.cloud.gateway.server.webmvc.routes[2].id=ms-cupones
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://ms-cupones
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/api/cupones/**
# ___
spring.cloud.gateway.server.webmvc.routes[3].id=user
spring.cloud.gateway.server.webmvc.routes[3].uri=lb://user
spring.cloud.gateway.server.webmvc.routes[3].predicates[0]=Path=api/auth/**

spring.cloud.gateway.server.webmvc.routes[4].id=menu
spring.cloud.gateway.server.webmvc.routes[4].uri=lb://menu
spring.cloud.gateway.server.webmvc.routes[4].predicates[0]=Path=/api/productos**

spring.cloud.gateway.server.webmvc.routes[5].id=pago
spring.cloud.gateway.server.webmvc.routes[5].uri=lb://pago
spring.cloud.gateway.server.webmvc.routes[5].predicates[0]=Path=/api/pagos/**

spring.cloud.gateway.server.webmvc.routes[6].id=fidelidad
spring.cloud.gateway.server.webmvc.routes[6].uri=lb://fidelidad
spring.cloud.gateway.server.webmvc.routes[6].predicates[0]=Path=/fidelidad/**

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}
eureka.instance.prefer-ip-address=true
